#
# Don't touch it!
#
version: "1.0.1-bugfix"

#
# Cooldown setting
#
cooldown:
  # Cooldown time in second
  # Set to 0 to disable
  time: 3
  # When cooldown is active on that player
  # Placeholders:
  # - %player% : the name of that player
  # - %cdtime% : cooldown time left
  message: "&7[&6ShiftHotkey&7] &cHotkey cooldown! Wait &d%cdtime% &cmore second to do this action again!"
#
# Hotkey setting
#
hotkeys:
  # Press SHIFT and Q
  shift-q:
    enable: false
    shift: true
    cancel-event: true
    # No need "/"
    commands:
      - "command1here"
      - "command2here andargs"
  # Press SHIFT and F
  shift-f:
    enable: false
    shift: true
    cancel-event: true
    # No need "/"
    commands:
      - ""